### ISSUE TITLE
Ingame name bug

### ISSUE THREAD

**Issue by Dunciboy** [IceNinjaman/CoD4X17a_testing#62]
using &&1  in your ingame name while being alive makes the text that user types appear at the place where &&1 is supposed to be. This bug does not effect self.name but does affect the the in game chat messages. disallowing names with &&1 would be the best and fastest solution.
![iw3mp 2015-02-18 14-55-49-69](https://cloud.githubusercontent.com/assets/10881109/6248292/825792a4-b77e-11e4-9405-4210c9181c76.jpg)

**Comment by k4r3l01** [comment]
why you using &&1 in iprintln??? just usel self.name &&1 works only with iprinlnbold,hud elements and menu files i think because this elements could use localized strings but iprintln and say not

**Comment by Ingramz** [comment]
k4r3l01, incorrect. &&1 ..9 works with iprintln too. It has very little to nothing to do with localized strings in fact. &&1...9 is used in a similar manner to printf in C-like languages.

Consider these two examples:
`iprintln("&&1 has dropped the bomb at position &&2", self.name, self.origin);`

and let's say there is a localized string
MP_DROP_BOMB_POS = "&&1 has dropped the bomb at position &&2"

`iprintln(&"MP_DROP_BOMB_POS", self.name, self.origin);`

Localized string exploits, 'print' functions' feature.

---

The issue is that &&1 is not sanitized correctly. This is similar to double wrapping colors in names eg. ^^33

**Comment by k4r3l01** [comment]
so i'm never used this but when i watch to cod4x code so iprintln using original function of cod not writed function by ninja

**Comment by Dunciboy** [comment]
![glitch](https://cloud.githubusercontent.com/assets/10881109/6289180/8296605a-b91e-11e4-9761-b7f26a27953f.png)

As exmaple here i'm using the name &&1&&2&&3&&4&&5 (max char limit reached)
The rankup message is completely messed up as you can see. and since the chat usses the &&1 loclized sting you get these bugs.

**Comment by IceNinjaman** [comment]
&& in usernames are disallowed now.
